### ISSUE TITLE
你反编译的怎么好意思把作者名字改成自己的

### ISSUE THREAD

**Issue by Lepton-Lee** [zfkun/ja-netfilter-mymap-plugin#4]
![image](https://user-images.githubusercontent.com/95926073/147614114-42d1018d-68d4-4b48-b689-e0f4687c82bb.png)
原作者明显是https://jetbra.in/s
在neo的微信公众号上有提供下载渠道

**Comment by Lepton-Lee** [comment]
https://jetbra.in/test-d1e437b41f00be320195e43180ffec963d734dea.html

**Comment by zfkun** [comment]
> 

多谢提醒哈。

😄   我稍后在README里加下说明，是基于反编译的版本，不然真可能会被喷死。

> 其实 我同步 [博文](https://www.zfkun.com/ja-netfilter-mymapy-plugin.html#ja-netfilter-mymap-plugin) 里也说了情况了，只单纯怕挂马，所以反编译自用，后考虑仍出来有需要人自用

**Comment by yhan219** [comment]
> ![image](https://user-images.githubusercontent.com/95926073/147614114-42d1018d-68d4-4b48-b689-e0f4687c82bb.png) 原作者明显是https://jetbra.in/s 在neo的微信公众号上有提供下载渠道

请问下neo公众号全称是什么？没搜到

**Comment by Lepton-Lee** [comment]
> > ![image](https://user-images.githubusercontent.com/95926073/147614114-42d1018d-68d4-4b48-b689-e0f4687c82bb.png) 原作者明显是https://jetbra.in/s 在neo的微信公众号上有提供下载渠道
> 
> 请问下neo公众号全称是什么？没搜到

neo博客主页有二维码https://zhile.io/

**Comment by yhan219** [comment]
> 

原来是zhile大神，感谢
