### ISSUE TITLE
linux 下面有问题

### ISSUE THREAD

**Issue by redseabay** [zfkun/ja-netfilter-mymap-plugin#9]
ja-netfilter 2.0.1 + mymap 1.1.2, 同样的配置, windows  下面可以激活, linux 下面就不行. clion & goland 2021.2.3 2021.3 2021.3.2 都试过.

换成 ja-netfilter 1.0.2 + mymap 1.0.1 两个平台都可以.

os 是: debian 11, kde

**Comment by zfkun** [comment]
> 

有报错日志吗？
> 加下 `-Djanf.debug=1` 开启下调试日志看看

**Comment by redseabay** [comment]
哦, 不止是 linux 下面有问题, 今天 windows 下面使用的激活码超期了, clion 和 goland 也不能使用了, 换了 ja netfilter 1.2 加 mymap 1.0.1 可以.

这个 -Djanf.debug=1 是加载 vmoptions 里面吗 ?

**Comment by Dawneng** [comment]
> 哦, 不止是 linux 下面有问题, 今天 windows 下面使用的激活码超期了, clion 和 goland 也不能使用了, 换了 ja netfilter 1.2 加 mymap 1.0.1 可以.
> 
> 这个 -Djanf.debug=1 是加载 vmoptions 里面吗 ?


**两个解决方法**

1. 换个激活码
2. 使用power插件（配置好参数）

**Comment by zfkun** [comment]
> 

是的。
的确，激活码 一定时间会失效的，网上可以搜下很多新的激活码的，替换一下就可以的

**Comment by zfkun** [comment]
文档里的 gracePeriodDays 只是随手写的 30，可以换成更大的值比如 100000，就够用了
